// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// hub75_stream //
// ------------ //

#define hub75_stream_wrap_target 0
#define hub75_stream_wrap 2
#define hub75_stream_pio_version 0

static const uint16_t hub75_stream_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 0
    0x7006, //  1: out    pins, 6         side 0
    0xb942, //  2: nop                    side 1 [1]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program hub75_stream_program = {
    .instructions = hub75_stream_program_instructions,
    .length = 3,
    .origin = -1,
    .pio_version = hub75_stream_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config hub75_stream_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + hub75_stream_wrap_target, offset + hub75_stream_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

